/**
 * Action types for game state reducer
 */

// Phase management
export const SET_PHASE = 'SET_PHASE';

// Game configuration
export const UPDATE_GAME_CONFIG = 'UPDATE_GAME_CONFIG';
export const SET_GAME_CONFIG = 'SET_GAME_CONFIG';

// Difficulty and resources
export const SET_DIFFICULTY = 'SET_DIFFICULTY';
export const SET_REQUISITION = 'SET_REQUISITION';
export const ADD_REQUISITION = 'ADD_REQUISITION';
export const SPEND_REQUISITION = 'SPEND_REQUISITION';

// Faction and subfaction
export const SET_SUBFACTION = 'SET_SUBFACTION';

// Draft slot locking (per-player)
export const LOCK_PLAYER_DRAFT_SLOT = 'LOCK_PLAYER_DRAFT_SLOT';
export const UNLOCK_PLAYER_DRAFT_SLOT = 'UNLOCK_PLAYER_DRAFT_SLOT';

// Samples
export const ADD_SAMPLES = 'ADD_SAMPLES';
export const RESET_SAMPLES = 'RESET_SAMPLES';
export const SET_SAMPLES = 'SET_SAMPLES';

// Players management
export const SET_PLAYERS = 'SET_PLAYERS';
export const UPDATE_PLAYER = 'UPDATE_PLAYER';
export const UPDATE_PLAYER_LOADOUT = 'UPDATE_PLAYER_LOADOUT';
export const ADD_ITEM_TO_PLAYER = 'ADD_ITEM_TO_PLAYER';
export const ADD_ARMOR_COMBO_TO_PLAYER = 'ADD_ARMOR_COMBO_TO_PLAYER';
export const SET_PLAYER_WARBONDS = 'SET_PLAYER_WARBONDS';
export const SET_PLAYER_SUPERSTORE = 'SET_PLAYER_SUPERSTORE';
export const SET_PLAYER_EXCLUDED_ITEMS = 'SET_PLAYER_EXCLUDED_ITEMS';
export const SET_PLAYER_EXTRACTED = 'SET_PLAYER_EXTRACTED';
export const SACRIFICE_ITEM = 'SACRIFICE_ITEM';

// Draft state
export const SET_DRAFT_STATE = 'SET_DRAFT_STATE';
export const UPDATE_DRAFT_STATE = 'UPDATE_DRAFT_STATE';
export const SET_DRAFT_CARDS = 'SET_DRAFT_CARDS';
export const SET_ACTIVE_PLAYER_INDEX = 'SET_ACTIVE_PLAYER_INDEX';
export const SET_PENDING_STRATAGEM = 'SET_PENDING_STRATAGEM';
export const DRAFT_PICK = 'DRAFT_PICK'; // Multiplayer action for client draft picks
export const STRATAGEM_REPLACEMENT = 'STRATAGEM_REPLACEMENT'; // Multiplayer action for stratagem slot replacement

// Sacrifice state
export const SET_SACRIFICE_STATE = 'SET_SACRIFICE_STATE';
export const UPDATE_SACRIFICE_STATE = 'UPDATE_SACRIFICE_STATE';

// Events
export const SET_CURRENT_EVENT = 'SET_CURRENT_EVENT';
export const SET_EVENT_PLAYER_CHOICE = 'SET_EVENT_PLAYER_CHOICE';
export const SET_EVENTS_ENABLED = 'SET_EVENTS_ENABLED';
export const ADD_SEEN_EVENT = 'ADD_SEEN_EVENT';
export const RESET_SEEN_EVENTS = 'RESET_SEEN_EVENTS';
export const SET_EVENT_STRATAGEM_SELECTION = 'SET_EVENT_STRATAGEM_SELECTION';
export const SET_EVENT_TARGET_PLAYER_SELECTION = 'SET_EVENT_TARGET_PLAYER_SELECTION';
export const SET_EVENT_TARGET_STRATAGEM_SELECTION = 'SET_EVENT_TARGET_STRATAGEM_SELECTION';
export const SET_EVENT_BOOSTER_DRAFT = 'SET_EVENT_BOOSTER_DRAFT';
export const SET_EVENT_BOOSTER_SELECTION = 'SET_EVENT_BOOSTER_SELECTION';
export const SET_EVENT_SPECIAL_DRAFT = 'SET_EVENT_SPECIAL_DRAFT';
export const SET_EVENT_SPECIAL_DRAFT_TYPE = 'SET_EVENT_SPECIAL_DRAFT_TYPE';
export const SET_EVENT_SPECIAL_DRAFT_SELECTIONS = 'SET_EVENT_SPECIAL_DRAFT_SELECTIONS';
export const SET_EVENT_SPECIAL_DRAFT_SELECTION = 'SET_EVENT_SPECIAL_DRAFT_SELECTION';
export const SET_PENDING_FACTION = 'SET_PENDING_FACTION';
export const SET_PENDING_SUBFACTION_SELECTION = 'SET_PENDING_SUBFACTION_SELECTION';
export const RESET_EVENT_SELECTIONS = 'RESET_EVENT_SELECTIONS';

// Custom setup
export const SET_CUSTOM_SETUP = 'SET_CUSTOM_SETUP';
export const UPDATE_CUSTOM_SETUP = 'UPDATE_CUSTOM_SETUP';
export const SET_SELECTED_PLAYER = 'SET_SELECTED_PLAYER';

// Burn cards
export const ADD_BURNED_CARD = 'ADD_BURNED_CARD';
export const SET_BURNED_CARDS = 'SET_BURNED_CARDS';

// Endurance mode
export const SET_CURRENT_MISSION = 'SET_CURRENT_MISSION';

// Full state load
export const LOAD_GAME_STATE = 'LOAD_GAME_STATE';
export const RESET_GAME = 'RESET_GAME';
